services:
  strfry-nostr-relay:
    image: sebastianmontero/strfry:e4e79af1214e38ea90f4d099bd1f057a688abdb6
    volumes:
      - ./strfry.conf:/etc/strfry.conf
      - strfry-db:/app/strfry-db
    ports:
      - "7777:7777"
volumes:
  strfry-db: